### PR TITLE
Try opening emacsclient before starting new Emacs instance

### LINKED ISSUE #1: emacsclient support
https://github.com/prathik/emacs-anywhere/blob/f10e783dd0603ed8750bd3588ee90d9489620ba0/bin/run#L56

would be good to add a configuration option or open by default `emacsclient` instead of the emacs instance.

I did this to open a new `emacsclient` frame:
```
/usr/local/bin/emacsclient -c $TMPFILE
```

### PR DESCRIPTION
**Pull request by larstvei**
This fixes #1 for me at least.

It should probably be generalized or made customizable.

### CODE REVIEW

**Comment by prathik** [comment]
doesn't seem to be working for me.

I started emacs in server-mode and then hit cmd-ctrl-v and was expecting the file to come up on the emacs server. 

You could also consider open -a Emacs --args --eval "(server-start)" $TMPFILE to auto start the server at the beginning.

**Comment by larstvei** [comment]
How did it not work?

If a server is running, then what should happen is that the file opens in a new Emacs frame (which you can close with `C-x #`). Did this happen?

If no server is running (or you don't have `emacsclient` installed), then the program should function as originally intended (open a new instance of Emacs and add text to clipboard on quit). Did this happen?

As far as I understand the `open -a Emacs --args --eval "(server-start)" $TMPFILE` defeats the purpose, because if you don't have a server running at the time you run the cmd-ctrl-v, then you might as well open a new instance?

**Comment by prathik** [comment]
Here is what I did - started emacs with server on terminal, hit cmd-ctrl-v, however a new GUI instance loaded. However changing from emacsclient -c $TMPFILE to emacsclient $TMPFILE is working.

**Comment by prathik** [comment]
@larstvei I have tested without the `-c` option and it's working, let me know if that works for you as well.

**Comment by prathik** [comment]
Hey the PR auto-closed because I had to rewrite the git history. Can you want to raise a new PR if the emacsclient solve works?

**Comment by larstvei** [comment]
The `emacsclient -c` worked as expected. It spawns a new frame, but attaches to the running Emacs server. So it is not a new instance of Emacs, meaning that the init file is not loaded again (which is important if you have a init file which takes several seconds to load).

I would argue that opening a new Emacs frame but connecting to the same running instance is nicer than switching to the existing window (which could be fullscreen in another space).

**Comment by prathik** [comment]
`emacsclient -c` isn't working for me, the service starts and ends, I don't see a place where I can add content anywhere.

**Comment by prathik** [comment]
I agree that new frame is better, however isn't working for me.

**Comment by larstvei** [comment]
Sorry, I misread your previous comment.

It would be nice to know why it doesn't work for you. Could you see what happens if you just invoke the command manually?

I think the solution is really to make the command customizable. Perhaps keep the command in an environment variable?

**Comment by prathik** [comment]
`/usr/local/bin/emacsclient: could not get terminal name` this is the error I get when I invoke emacsclient via the script. Works fine when I run directly in the terminal though.

**Comment by prathik** [comment]
I reinstalled emacs and is working fine. Can you raise a new PR? I'll merge the changes.

**Comment by prathik** [comment]
I had to push a fix in the install script and pushed the emacsclient change along with it. Cheers!

**Comment by larstvei** [comment]
Nice, thanks!

**Pull request closed without merging**
